baseURL = "https://smylingsas.net/"
languageCode = "no-nb"
languageLang = "no"
title = ""
# filesystem path to write files to
publishDir = "public"
# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration

canonifyURLs = "false"
uglyURLs = "false"

[params]
    owner = "Ole Halvor Smylingsås"
    dateform        = "Jan 2, 2006"
    favicon = "favicon.svg"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04 -0700"
    description = "Hjemmeside og blog for Ole Halvor Smylingsås"
    keywords = "hjemmeside, blog, utvikling, programering"

[params.sociallinks]
[[params.sociallinks.developer]]
	name = "GitHub"
	url = "https://github.com/olehsm"
	icon = "fab fa-github"
  desc = "Følg meg på Github"
[[params.sociallinks.developer]]
	name = "Instagram"
	url = "https://instagram.com/habbheim"
	icon = "fab fa-instagram"
  desc = "Følg meg på Instagram"
[[params.sociallinks.developer]]
	name ="Twitter"
	url = "https://twitter.com/olehsm"
	icon = "fab fa-twitter"
  desc = "Følg meg på Twitter"


[menu]
  [[menu.main]]
    name = "Hjem"
    pre = "<i class='fas fa-home'></i>"
    url = "/"
    weight = -140
  [[menu.main]]
    name = "Prosjekter"
    pre = "<i class='fas fa-project-diagram'></i>"
    url = "/projects/"
    weight = -110
  [[menu.main]]
    name = "Artikler"
    pre = "<i class='fas fa-list'></i>"
    url = "/writings/"
    weight = -97
  [[menu.main]]
    name = "Bokmerker"
    pre = "<i class='fa fa-star'></i>"
    url = "/bookmarks/"
    weight = -120