baseURL = "https://smylingsas.net/"
languageCode = "no-nb"
languageLang = "no"
title = "Smylingsas.net"
# filesystem path to write files to
publishDir = "public"
# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration

canonifyURLs = "false"
uglyURLs = "false"

[params]
    googleAnalytics = "UA-123-45"
    disqusShortname = "yourdiscussshortname"
    owner = "Ole Halvor Smylingsås"
    dateform        = "Jan 2, 2006"
    favicon = "favicon.ico"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04 -0700"
    description = "Hjemmeside og blog for Ole Halvor Smylingsås"
    keywords = "hjemmeside, blog, utvikling, programering"
    mainSections = ["blog", "til"]

[params.sociallinks]
[[params.sociallinks.developer]]
	name = "GitHub"
	url = "https://github.com/olehsm"
	icon = "fab fa-github"
  desc = "Følg meg på Github"
[[params.sociallinks.developer]]
	name = "Instagram"
	url = "https://instagram.com/habbheim"
	icon = "fab fa-instagram"
  desc = "Følg meg på Instagram"
[[params.sociallinks.developer]]
	name ="Twitter"
	url = "https://twitter.com/olehsm"
	icon = "fab fa-twitter"
  desc = "Følg meg på Twitter"


[menu]

  [[menu.main]]
    name = "Arkiv"
    pre = "<i class='fa fa-heart'></i>"
    url = "/archives/"
    weight = -120

  [[menu.main]]
    name = "Prosjekter"
    pre = "<i class='fa fa-heart'></i>"
    url = "/projects/"
    weight = -110

  [[menu.main]]
    name = "TIL"
    pre = "<i class='fa fa-road'></i>"
    url = "/til/"
    weight = -100

    [[menu.main]]
    name = "Topics"
    pre = "<i class='fa fa-heart'></i>"
    url = "/tags/"
    weight = -99

    [[menu.main]]
    name = "Artikler"
    pre = "<i class='fa fa-heart'></i>"
    url = "/articles/"
    weight = -97

    [[menu.main]]
    name = "Sitemap.xml"
    pre = "<i class='fa fa-heart'></i>"
    url = "/sitemap.xml/"
    weight = -90
    target = "_blank"

  [[menu.main]]
    name = "Humans.txt"
    pre = "<i class='fa fa-road'></i>"
    url = "/humans.txt/"
    weight = -80
    target = "_blank"
