baseURL = "https://smylingsas.net/"
languageCode = "no-nb"
languageLang = "no"
title = ""
# filesystem path to write files to
publishDir = "public"
# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration

canonifyURLs = "false"
uglyURLs = "false"
enableGitInfo = true

[params]
    owner = "Ole Halvor Smylingsås"
    dateform        = "Jan 2, 2006"
    favicon = "favicon.svg"
    themecolor = "#eff0f3"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04 -0700"
    description = "Hjemmeside og blog for Ole Halvor Smylingsås"
    keywords = "hjemmeside, blog, utvikling, programering"

[params.sociallinks]
[[params.sociallinks.developer]]
	name = "GitHub"
	url = "https://github.com/olehsm"
	icon = ""
  desc = "Følg meg på Github"
[[params.sociallinks.developer]]
	name = "Instagram"
	url = "https://instagram.com/habbheim"
	icon = ""
  desc = "Følg meg på Instagram"
[[params.sociallinks.developer]]
	name ="X"
	url = "https://x.com/olehsm"
	icon = "&#120143;"
  desc = "Følg meg på X"


[menu]
  [[menu.main]]
    name = "Hjem"
    pre = "<i>&#x2302;</i>"
    url = "/"
    weight = -140
  [[menu.main]]
    name = "Prosjekter"
    pre = "<i>&#x1F6E0;</i>"
    url = "/projects/"
    weight = -110
  [[menu.main]]
    name = "Blog"
    pre = "<i>&#128395;</i>"
    url = "/writings/"
    weight = -97
  [[menu.main]]
    name = "Bokmerker"
    pre = "<i>&#128366;</i>"
    url = "/bookmarks/"
    weight = -120

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'github'
    tabWidth = 4