baseURL = "https://smylingsas.net/"
languageCode = "en-us"
languageLang = "en"
title = "Smylingsas.net"
# filesystem path to write files to
publishDir = "../public"
# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration

canonifyURLs = "false"
uglyURLs = "false"

[params]
    twitteruser = "olehsm"
    githubuser = "olehsm"
    instagramuser = "habbheim"
    googleAnalytics = "UA-123-45"
    disqusShortname = "yourdiscussshortname"
    owner = "Ole Halvor Smylingsås"
    dateform        = "Jan 2, 2006"
    favicon = "favicon.ico"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04 -0700"
    description = "Homepage and blog by Ole Halvor Smylingsås"
    keywords = "homepage, blog, development, programming"
    mainSections = ["blog", "til"]
