baseURL = "https://smylingsas.net/"
languageCode = "en-us"
languageLang = "en"
title = "Smylingsas.net"
# filesystem path to write files to
publishDir = "../public"
# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
canonifyURLs = "true"

[params]
    twitteruser = "olehsm"
    githubuser = "olehsm"
    instagramuser = "habbheim"
    googleAnalytics = "UA-123-45"
    disqusShortname = "yourdiscussshortname"
    owner = "Ole Halvor Smylingsås"
    dateform        = "Jan 2, 2006"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04 -0700"
    description = "Homepage and blog by Ole Halvor Smylingsås"
    keywords = "homepage, blog, development, programming"
    images = [""]
    mainSections = ["blog", "til"]

[deployment]
    # By default, files are uploaded in an arbitrary order.
    # Files that match the regular expressions in the "Order" list
    # will be uploaded first, in the listed order.
    order = [".jpg$", ".gif$"]

[[deployment.targets]]
    # An arbitrary name for this target.
        name = "mydeployment"
    # The Go Cloud Development Kit URL to deploy to. Examples:
        URL = "s3://<Bucket Name>?region=<AWS region>"  # For S3; see https://gocloud.dev/howto/blob/open-bucket/#s3.    
    # If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
    cloudFrontDistributionID = "ID"

[[deployment.matchers]]
    #  Cache static assets for 20 years.
        pattern = "^.+\\.(js|css|svg|ttf)$"
        cacheControl = "max-age=630720000, no-transform, public"
        gzip = true
